name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  publish-npm:
    needs: release
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v3.0.0
      with:
        version: latest
        run_install: false

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'

    - run: pnpm i --frozen-lockfile

    - run: pnpm build

    - run: pnpm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        NPM_CONFIG_PROVENANCE: true